        <?php

        include 'file_functions.php';

        error_reporting(E_ALL);
        ini_set('display_errors', '1');

        //print_r($_POST); // Affichez les données POST reçues à des fins de débogage

        if ($_SERVER["REQUEST_METHOD"] == "POST") {
            $date = date('Ymd'); // Obtenez la date et l'heure actuelles
            $category_indicator = $_POST['category_indicator']; // Récupérez l'indicateur de catégorie depuis le formulaire
                // Répertoire d'upload spécifique à la catégorie
            $uploadDir = 'C:/xampp/htdocs/uploads/' . $category_indicator . '/';
            
            // Créez le répertoire s'il n'existe pas
            if (!is_dir($uploadDir)) {
                mkdir($uploadDir, 0777, true);
            }
            $uploadedFiles = $_FILES['images']['name'];
            $uploadedFileNames = implode(",", $uploadedFiles);

            if ($_FILES && $_FILES['images']) {
                // Chemin vers le répertoire d'upload des images
                $uploadDir = 'C:/xampp/htdocs/uploads/' . $category_indicator . '/';

                if (!empty($_FILES['images']['name'][0])) {
                    $zip = new ZipArchive();
                    $zip_name = $uploadDir . $category_indicator . "_" . $date . ".zip"; // Ajoutez la date au nom du fichier ZIP
                    
                    // Créez un fichier ZIP
                    if ($zip->open($zip_name, ZipArchive::CREATE) !== TRUE) {
                        $error .= "Désolé, la création du fichier ZIP ne fonctionne pas actuellement.<br/>";
                    }

                    $imageCount = count($_FILES['images']['name']);
                    for ($i = 0; $i < $imageCount; $i++) {
                        if ($_FILES['images']['tmp_name'][$i] == '') {
                            continue;
                        }
                        $newname = $date . mt_rand() . '.jpg';
                        $zip->addFromString($_FILES['images']['name'][$i], file_get_contents($_FILES['images']['tmp_name'][$i]));
                    }
                    $zip->close();

                    // Succès - Nom du fichier ZIP pour le téléchargement
                    $success = basename($zip_name);
                } else {
                    $error = '<strong>Erreur!! </strong> Veuillez sélectionner un fichier.';
                }
            }

        $categories = [
            'claviers' => [
                'header' => ["category_ids", "sku", "name", "short_description", "description", "price", "special_price", "is_in_stock", "stock", "weight", "shipping_cost", "grade_du_produit", "garantie_en_mois", "durai_de_livraison_jours", "rgb", "clavier_retro_eclaire", "clavier_mecanique", "sans_fil", "type_clavier", "pave_numerique", "meta_title", "meta_keyword", "meta_description", "images"],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                    $_POST["weight"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    $_POST["rgb"],
                    $_POST["clavier_retro_eclaire"],
                    $_POST["clavier_mecanique"],
                    $_POST["sans_fil"],
                    $_POST["type_clavier"],
                    $_POST["pave_numerique"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames, 
                ]
            ],

            'ordinateurs-bureau'=>[
                'header'=>["category_ids","sku","name","short_description","description","price","special_price","is_in_stock","stock","weight","shipping_cost","grade_du_produit","garantie_en_mois","durai_de_livraison_jours","rgb","gpu","psu","stockage","cpu","vr_ready","ram","systeme","stockage_memoire","cpu_info","couleur_pc","meta_title","meta_keyword","meta_description","images"],
                'csv_data' => [
                    '"'.$_POST["category_ids[]"].'"',
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                $_POST["special_price"],
                $_POST["is_in_stock"],
                $_POST["stock"],
                $_POST["weight"],
                $_POST["shipping_cost"],
                $_POST["grade_du_produit"],
                $_POST["garantie_en_mois"],
                $_POST["durai_de_livraison_jours"],
                $_POST["rgb"],
                $_POST["gpu"],
                $_POST["psu"],
                $_POST["stockage"],
                $_POST["cpu"],
                $_POST["vr_ready"],
                $_POST["ram"],
                $_POST["systeme"],
                $_POST["stockage_memoire"],
                $_POST["cpu_info"],
                $_POST["couleur_pc"],
                '"'.$_POST["meta_title"].'"',
                '"'.$_POST["meta_keyword"].'"',
                '"'.$_POST["meta_description"].'"',
                $uploadedFileNames,
                ]

            ],
            'laptop'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "cpu",
                "cpu_info",
                "ram",
                "stockage",
                "stockage_memoire",
                "gpu",
                "taille_ecran",
                "Tactile",
                "type_clavier",
                "clavier_retro_eclaire",
                "systeme",
                "couleur_pc",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    '"'.$_POST["category_ids[]"].'"',
            '"'.$_POST["sku"].'"',
            '"'.$_POST["laptop_name"].'"',
            '"'.$_POST["short_description"].'"',
            '"'.$_POST["description"].'"',
            $_POST["price"],
            $_POST["special_price"],
            $_POST["is_in_stock"],
            $_POST["stock"],
            $_POST["weight"],
            $_POST["shipping_cost"],
            $_POST["grade_du_produit"],
            $_POST["garantie_en_mois"],
            $_POST["durai_de_livraison_jours"],
            $_POST["cpu"],
            $_POST["cpu_info"],
            $_POST["ram"],
            $_POST["stockage"],
            $_POST["stockage_memoire"],
            $_POST["gpu"],
            $_POST["taille_ecran"],
            $_POST["Tactile"],
            $_POST["type_clavier"],
            $_POST["clavier_retro_eclaire"],
            $_POST["systeme"],
            $_POST["couleur_pc"],
            '"'.$_POST["meta_title"].'"',
            '"'.$_POST["meta_keyword"].'"',
            '"'.$_POST["meta_description"].'"',
            $uploadedFileNames,
                ]

            ],
            'Smartphones'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "stockage",
                "double_sim",
                "sd-card",
                "with_charger",
                "taille_ecran",
                "systeme",
                "batterie",
                "network_?G",
                "vr-operator",
                "vr-to-operator",
                "color",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    '"'.$_POST["category_ids[]"].'"',
            '"'.$_POST["sku"].'"',
            '"'.$_POST["laptop_name"].'"',
            '"'.$_POST["short_description"].'"',
            '"'.$_POST["description"].'"',
            $_POST["price"],
            $_POST["special_price"],
            $_POST["is_in_stock"],
            $_POST["stock"],
            $_POST["weight"],
            $_POST["shipping_cost"],
            $_POST["grade_du_produit"],
            $_POST["garantie_en_mois"],
            $_POST["durai_de_livraison_jours"],
            $_POST["batterie"],
            $_POST["stockage"],
            $_POST["double_sim"],
            $_POST["sd-card"],
            $_POST["with_charger"],
            $_POST["network_?G"],
            $_POST["taille_ecran"],
            $_POST["vr-operator"],
            $_POST["vr-to-operator"],
            $_POST["systeme"],
            $_POST["color"],
            '"'.$_POST["meta_title"].'"',
            '"'.$_POST["meta_keyword"].'"',
            '"'.$_POST["meta_description"].'"',
            $uploadedFileNames,
                ]

            ],
            'MacBook'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "cpu",
                "cpu_info",
                "ram",
                "stockage",
                "stockage_memoire",
                "gpu",
                "taille_ecran",
                "Tactile",
                "type_clavier",
                "batterie",
                "retina",
                "touch_bar",
                "clavier_retro_eclaire",
                "systeme",
                "couleur_pc",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    '"'.$_POST["category_ids[]"].'"',
            '"'.$_POST["sku"].'"',
            '"'.$_POST["laptop_name"].'"',
            '"'.$_POST["short_description"].'"',
            '"'.$_POST["description"].'"',
            $_POST["price"],
            $_POST["special_price"],
            $_POST["is_in_stock"],
            $_POST["stock"],
            $_POST["weight"],
            $_POST["shipping_cost"],
            $_POST["grade_du_produit"],
            $_POST["garantie_en_mois"],
            $_POST["durai_de_livraison_jours"],
            $_POST["cpu"],
            $_POST["cpu_info"],
            $_POST["ram"],
            $_POST["stockage"],
            $_POST["stockage_memoire"],
            $_POST["gpu"],
            $_POST["taille_ecran"],
            $_POST["Tactile"],
            $_POST["batterie"],
            $_POST["retina"],
            $_POST["touch_bar"],
            $_POST["type_clavier"],
            $_POST["clavier_retro_eclaire"],
            $_POST["systeme"],
            $_POST["couleur_pc"],
            '"'.$_POST["meta_title"].'"',
            '"'.$_POST["meta_keyword"].'"',
            '"'.$_POST["meta_description"].'"',
            $uploadedFileNames,
                ]

            ],
            'pos'=>[
                'header'=>[ "category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "taille_ecran", 
                "port_affichage",
                "ram",
                "Tactile",
                "stockage_option",
                "stockage",
                "taille_ecran",
                "serial_port",
                "usb_port",
                "nb_drawer_port",
                "ethernet_port",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                        $_POST["price"],
                        $_POST["special_price"],
                        $_POST["is_in_stock"],
                        $_POST["stock"],
                        $_POST["weight"],
                        $_POST["shipping_cost"],
                        $_POST["grade_du_produit"],
                        $_POST["garantie_en_mois"],
                        $_POST["durai_de_livraison_jours"],
                        $_POST["taille_ecran"],
                        $_POST["port_affichage"],
                        $_POST["ram"],
                        $_POST["Tactile"],
                        $_POST["stockage_option"],
                        $_POST["stockage"],
                        $_POST["taille_ecran"],
                        $_POST["serial_port"],
                        $_POST["usb_port"],
                        $_POST["nb_drawer_port"],
                        $_POST["ethernet_port"],
                        '"'.$_POST["meta_title"].'"',
                        '"'.$_POST["meta_keyword"].'"',
                        '"'.$_POST["meta_description"].'"',
                        $uploadedFileNames,
                ]
            ],
            'Imprimantes-scanner'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "types_imprimantes",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                    $_POST["weight"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    $_POST["types_imprimantes"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames,
                ]

            ],
            'moniteurs'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "taille_ecran",
                "resolution",
                "port_affichage",
                "incurvee",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                    $_POST["weight"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    $_POST["taille_ecran"],
                    $_POST["resolution"],
                    $_POST["port_affichage"],
                    $_POST["incurvee"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames,
                ]

            ],
            'reseau'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
            '"'.$_POST["sku"].'"',
            '"'.$_POST["name"].'"',
            '"'.$_POST["short_description"].'"',
            '"'.$_POST["description"].'"',
            $_POST["price"],
            $_POST["special_price"],
            $_POST["is_in_stock"],
            $_POST["stock"],
            $_POST["weight"],
            $_POST["shipping_cost"],
            $_POST["grade_du_produit"],
            $_POST["garantie_en_mois"],
            $_POST["durai_de_livraison_jours"],
            '"'.$_POST["meta_title"].'"',
            '"'.$_POST["meta_keyword"].'"',
            '"'.$_POST["meta_description"].'"',
            $uploadedFileNames,
                ]

            ],
            'souris'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "rgb",
                "sans_fil",
                "dpi_de_la_souris",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
            '"'.$_POST["sku"].'"',
            '"'.$_POST["name"].'"',
            '"'.$_POST["short_description"].'"',
            '"'.$_POST["description"].'"',
            $_POST["price"],
            $_POST["special_price"],
            $_POST["is_in_stock"],
            $_POST["stock"],
            $_POST["weight"],
            $_POST["shipping_cost"],
            $_POST["grade_du_produit"],
            $_POST["garantie_en_mois"],
            $_POST["durai_de_livraison_jours"],
            $_POST["rgb"],
            $_POST["sans_fil"],
            $_POST["dpi_de_la_souris"],
            '"'.$_POST["meta_title"].'"',
            '"'.$_POST["meta_keyword"].'"',
            '"'.$_POST["meta_description"].'"',
            $uploadedFileNames,
                ]

            ],
            'moniteurs'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "taille_ecran",
                "resolution",
                "port_affichage",
                "incurvee",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                    $_POST["weight"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    $_POST["taille_ecran"],
                    $_POST["resolution"],
                    $_POST["port_affichage"],
                    $_POST["incurvee"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames,
                ]

            ],
            'Audio-son'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "sans_fil",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                        $_POST["weight"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    $_POST["sans_fil"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames,
                ]

            ],
            'boitiers'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                    $_POST["weight"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames,
                ]

            ],
            
            'Cartes graphiques'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                    $_POST["weight"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames,
                ]

            ],
            'Cartes_meres'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                    $_POST["weight"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames,
                ]

            ],
            'Console Stockage variable'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "stockage",
                "color",
                "mode_fl",
                "nbr_manette",
                "type_console",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                    $_POST["weight"],
                    $_POST["stockage"],
                    $_POST["color"],
                    $_POST["mode_fl"],
                    $_POST["nbr_manette"],
                    $_POST["type_console"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames,
                ]

            ],
            'Consoles'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "stockage",
                "color",
                "mode_fl",
                "nbr_manette",
                "type_console",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                    $_POST["weight"],
                    $_POST["stockage"],
                    $_POST["color"],
                    $_POST["mode_fl"],
                    $_POST["nbr_manette"],
                    $_POST["type_console"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames,
                ]

            ],
            'Console Stockage variable'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "stockage",
                "color",
                "mode_fl",
                "nbr_manette",
                "type_console",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                    $_POST["weight"],
                    $_POST["stockage"],
                    $_POST["color"],
                    $_POST["mode_fl"],
                    $_POST["nbr_manette"],
                    $_POST["type_console"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames,
                ]

            ],
            'Default'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                    $_POST["weight"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames,
                ]

            ],
            'Mémoire RAM'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                    $_POST["weight"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames,
                ]

            ],
            'Processeurs'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                    $_POST["weight"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames,
                ]

            ],
            'Vidéo_camera'=>[
                'header'=>["category_ids",
                "sku",
                "name",
                "short_description",
                "description",
                "price",
                "special_price",
                "is_in_stock",
                "stock",
                "weight",
                "shipping_cost",
                "grade_du_produit",
                "garantie_en_mois",
                "durai_de_livraison_jours",
                "megapix",
                "color",
                "meta_title",
                "meta_keyword",
                "meta_description",
                "images",
            ],
                'csv_data' => [
                    $_POST["category_ids[]"],
                    '"'.$_POST["sku"].'"',
                    '"'.$_POST["name"].'"',
                    '"'.$_POST["short_description"].'"',
                    '"'.$_POST["description"].'"',
                    $_POST["price"],
                    $_POST["special_price"],
                    $_POST["is_in_stock"],
                    $_POST["stock"],
                    $_POST["weight"],
                    $_POST["shipping_cost"],
                    $_POST["grade_du_produit"],
                    $_POST["garantie_en_mois"],
                    $_POST["durai_de_livraison_jours"],
                    $_POST["megapix"],
                    $_POST["color"],
                    '"'.$_POST["meta_title"].'"',
                    '"'.$_POST["meta_keyword"].'"',
                    '"'.$_POST["meta_description"].'"',
                    $uploadedFileNames,
                ]

            ],
            
        ];

        if (array_key_exists($category_indicator, $categories)) {
            $category_data = $categories[$category_indicator];
            $category_upload_dir = 'C:/xampp/htdocs/uploads/' . $category_indicator . '/'; // Chemin vers le répertoire de la catégorie 
            $csv_file_path = $category_upload_dir . $category_indicator . "_" . $date . '.csv'; // Chemin du fichier CSV spécifique à la catégorie
            $csv_file = fopen($csv_file_path, "a");

            // Ajoutez un en-tête CSV si le fichier est vide
            if (filesize($csv_file_path) === 0) {
                fputs($csv_file, $bom = (chr(0xEF) . chr(0xBB) . chr(0xBF)));
                fputcsv($csv_file, $category_data['header']);
            }

            // Écrivez les données CSV
            fputcsv($csv_file, $category_data['csv_data']);

            fclose($csv_file);

            // Configurez les en-têtes appropriés pour le téléchargement du fichier
            header('Content-type: text/csv; charset=UTF-8');
            header("Content-Disposition: attachment; filename={$category_indicator}_{$date}.csv");
            header("Content-Length: " . filesize($csv_file_path));

            // Sortie du contenu du fichier
            readfile($csv_file_path);
            $message = "Le fichier CSV a été généré avec succès.";
        } else {
            $message = "Erreur : Catégorie non valide.";
        }

        echo json_encode(array("message" => $message));
        exit;
        }
        $uploadDir = 'C:/xampp/htdocs/uploads/'; // Chemin vers le répertoire des téléchargements

        ?>
